LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := hello
LOCAL_SRC_FILES := hello.cpp

LOCAL_C_INCLUDES := $(LOCAL_PATH)

LOCAL_CFLAGS += -DEGL_EGLEXT_PROTOTYPES
LOCAL_LDLIBS := -llog -lEGL -lGLESv2


include $(BUILD_EXECUTABLE)